export const identity = {
  url: 'https://ivaikin.com',
  name: 'Timothy Ivaikin',
  alternateName: 'Тимофей Ивайкин',
  email: 'hello@edgeivaikin.com',
  telegram: 'https://t.me/timothyivaikin',
  profiles: [
    ['LinkedIn', 'https://www.linkedin.com/in/timothyivaikin'],
    ['YouTube', 'https://www.youtube.com/@TimothyIvaikin'],
    ['GitHub', 'https://github.com/Ivajkin'],
    ['Medium', 'https://ivaikin.medium.com/'],
  ],
};

export const coreLocales = {
  en: {
    name: 'Timothy Ivaikin', nativeName: 'English', path: '/about/', locale: 'en_US',
    title: 'Timothy Ivaikin — Founder of Edge Ecosystem & EdgeFocus',
    description: 'Entrepreneur and founder of Edge Ecosystem. Timothy Ivaikin brings software, IT infrastructure and teams together to launch digital products and services.',
    skip: 'Skip to content', navLabel: 'Main navigation', languageLabel: 'Choose language',
    nav: ['Work', 'Ideas', 'Contact'],
    role: 'Entrepreneur. Founder. Author.',
    firstName: 'Timothy', lastName: 'Ivaikin',
    hero: 'Digital products. From business need to launch.',
    intro: 'I help owners and leaders launch products and services that need software, IT infrastructure and an organized team.',
    cta: 'Discuss a project', secondaryCta: 'Explore my work',
    portraitAlt: 'Portrait of Timothy Ivaikin', portraitCaption: 'Founder of Edge Ecosystem',
    identity: 'Founder of Edge Ecosystem. Creator of EdgeFocus with my team. Author of Good Results and Shattering Limits.',
    workEyebrow: 'What I build', workTitle: 'Business, technology and people. Connected.',
    workIntro: 'I lead technical delivery: from understanding the business need and assembling the team to implementation and acceptance of an agreed result.',
    ecosystemCategory: 'Company', ecosystemTitle: 'Edge Ecosystem',
    ecosystemBody: 'With my team, I build customer portals, internal systems and automation so customers can access services online, staff can work without repeated data entry and manual handoffs, and leaders can see the status of operations.',
    ecosystemExamples: ['Customer-facing services', 'Internal business systems', 'Integration & automation'],
    ecosystemLink: 'Explore Edge Ecosystem',
    focusCategory: 'Product', focusTitle: 'EdgeFocus',
    focusBody: 'A workspace for notes, goals, projects and actions. A product I created with my team to connect the bigger picture with everyday work.',
    focusExamples: ['Capture what matters', 'Connect it to a goal', 'Choose the next action'],
    focusLink: 'Explore EdgeFocus',
    philosophyEyebrow: 'The direction behind the work',
    philosophyTitle: 'More possibilities for people.',
    philosophyBody: 'I want the products I build to expand what people can do and improve how they live. That connects my work in technology with my interest in leadership and personal development.',
    methodEyebrow: 'Working together', methodTitle: 'Start with the result people need.',
    methods: [
      ['Understand the situation', 'Who will use the product? What needs to change? We define the problem, the intended outcome and the boundaries of the work.'],
      ['Connect the parts', 'Bring the software, infrastructure and people into one delivery plan, with clear responsibilities and dependencies.'],
      ['Put it into use', 'Agree how the result will be accepted, deliver in bounded stages and plan for the people who will operate it.'],
    ],
    ideasEyebrow: 'Writing & conversations', ideasTitle: 'The thinking behind the work.',
    interviewTag: 'Conversation', interviewTitle: 'Teams, systems and tai chi',
    interviewBody: 'A conversation about leadership, preparing the system behind the work, and growing without losing the people involved.',
    interviewMeta: '47 min · Russian audio · English subtitles', interviewLink: 'Explore the conversation',
    interviewPath: '/en/interviews/tai-chi-business/',
    booksLabel: 'Books', bookOneBody: 'Art of efficiency for powerful growth.', bookTwoBody: 'Self-improvement for success and empowerment.',
    bookLink: 'Book details', writingLink: 'Read my writing on Medium',
    faqTitle: 'A few useful answers',
    faqs: [
      ['Who is Timothy Ivaikin?', 'Timothy Ivaikin (Тимофей Ивайкин) is an entrepreneur, founder of Edge Ecosystem, creator of EdgeFocus with his team, and author of Good Results and Shattering Limits.'],
      ['What can we work on together?', 'Digital products and services that need software, IT infrastructure and a coordinated team: customer portals, internal systems, integrations and automation. Start with the business situation and the result you need.'],
      ['Can I invite you to an interview or event?', 'Yes. Send the topic, audience, format and proposed dates. Relevant themes include building digital products, leadership, delegation and organizing work.'],
    ],
    contactEyebrow: 'Get in touch', contactTitle: 'What are you building?',
    contactBody: 'Tell me what needs to work, who it is for, and where you are now. For a partnership, interview or speaking invitation, include the topic and the people involved.',
    telegramLabel: 'Message me on Telegram', emailLabel: 'Write an email',
    contactNote: 'A short, specific introduction is a good place to start.',
    footerNote: 'Technology. Leadership. Human possibility.', backTop: 'Back to top',
  },
  ru: {
    name: 'Тимофей Ивайкин', nativeName: 'Русский', path: '/ru/about/', locale: 'ru_RU',
    title: 'Тимофей Ивайкин — основатель Edge Ecosystem и EdgeFocus',
    description: 'Предприниматель и основатель Edge Ecosystem Тимофей Ивайкин. Объединяю программное обеспечение, IT-инфраструктуру и команду для запуска цифровых продуктов и услуг.',
    skip: 'Перейти к содержанию', navLabel: 'Основная навигация', languageLabel: 'Выбрать язык',
    nav: ['Проекты', 'Идеи', 'Связаться'],
    role: 'Предприниматель. Основатель. Автор.',
    firstName: 'Тимофей', lastName: 'Ивайкин',
    hero: 'Цифровые продукты: от бизнес-задачи до запуска.',
    intro: 'Помогаю собственникам и руководителям запускать продукты и услуги, для которых нужны программное обеспечение, IT-инфраструктура и организованная работа команды.',
    cta: 'Обсудить проект', secondaryCta: 'Посмотреть проекты',
    portraitAlt: 'Портрет Тимофея Ивайкина', portraitCaption: 'Основатель Edge Ecosystem',
    identity: 'Основатель Edge Ecosystem. Создатель EdgeFocus вместе с командой. Автор книг Good Results и Shattering Limits.',
    workEyebrow: 'Мои проекты', workTitle: 'Бизнес, технологии и люди. Вместе.',
    workIntro: 'Руковожу технической реализацией: от разбора бизнес-задачи и подбора команды до внедрения и приёмки согласованного результата.',
    ecosystemCategory: 'Компания', ecosystemTitle: 'Edge Ecosystem',
    ecosystemBody: 'Вместе с командой создаю клиентские порталы, внутренние системы и автоматизацию: чтобы клиенты могли получать услуги онлайн, сотрудники — выполнять операции без повторного ввода и ручной передачи данных, а руководители — видеть состояние работы.',
    ecosystemExamples: ['Клиентские онлайн-сервисы', 'Внутренние бизнес-системы', 'Интеграции и автоматизация'],
    ecosystemLink: 'О компании Edge Ecosystem',
    focusCategory: 'Продукт', focusTitle: 'EdgeFocus',
    focusBody: 'Рабочее пространство для заметок, целей, проектов и действий. Продукт, который мы создаём с командой, чтобы связывать общую картину с повседневной работой.',
    focusExamples: ['Сохранить важное', 'Связать с целью', 'Выбрать следующее действие'],
    focusLink: 'Познакомиться с EdgeFocus',
    philosophyEyebrow: 'Направление работы',
    philosophyTitle: 'Больше возможностей для человека.',
    philosophyBody: 'Я хочу, чтобы создаваемые мной продукты расширяли возможности людей и улучшали качество их жизни. Это связывает мою работу в технологиях с интересом к лидерству и развитию человека.',
    methodEyebrow: 'Как я работаю', methodTitle: 'Начать с нужного людям результата.',
    methods: [
      ['Разобраться в ситуации', 'Кто будет пользоваться продуктом? Что должно измениться? Определяем проблему, нужный результат и границы работы.'],
      ['Соединить части', 'Объединяем программное обеспечение, инфраструктуру и людей в план реализации с понятными зонами ответственности и зависимостями.'],
      ['Довести до использования', 'Согласуем способ приёмки, поставляем результат отдельными этапами и учитываем работу тех, кто будет им пользоваться.'],
    ],
    ideasEyebrow: 'Книги и разговоры', ideasTitle: 'Идеи за пределами продукта.',
    interviewTag: 'Разговор', interviewTitle: 'Команда, система и тайцзи',
    interviewBody: 'О лидерстве, подготовке системы за повседневной работой и росте, который сохраняет участвующих в нём людей.',
    interviewMeta: '47 минут · На русском · Есть английские субтитры', interviewLink: 'Открыть разговор',
    interviewPath: '/ru/interviews/tai-chi-business/',
    booksLabel: 'Книги', bookOneBody: 'Art of efficiency for powerful growth.', bookTwoBody: 'Self-improvement for success and empowerment.',
    bookLink: 'О книге', writingLink: 'Читать статьи на Medium',
    faqTitle: 'Несколько важных ответов',
    faqs: [
      ['Кто такой Тимофей Ивайкин?', 'Тимофей Ивайкин (Timothy Ivaikin) — предприниматель, основатель Edge Ecosystem, создатель EdgeFocus вместе с командой и автор книг Good Results и Shattering Limits.'],
      ['С чем можно обратиться?', 'С запуском цифровых продуктов и услуг, которым нужны программное обеспечение, IT-инфраструктура и согласованная работа команды: клиентских порталов, внутренних систем, интеграций и автоматизации. Начните с описания ситуации и нужного результата.'],
      ['Можно пригласить на интервью или выступление?', 'Да. Пришлите тему, аудиторию, формат и предполагаемые даты. Темы для разговора: создание цифровых продуктов, лидерство, делегирование и организация работы.'],
    ],
    contactEyebrow: 'Связаться', contactTitle: 'Что вы хотите создать?',
    contactBody: 'Расскажите, что должно заработать, для кого и на каком этапе вы сейчас. Для партнёрства, интервью или выступления — укажите тему и участников.',
    telegramLabel: 'Написать в Telegram', emailLabel: 'Написать на почту',
    contactNote: 'Короткое и конкретное знакомство — хорошее начало.',
    footerNote: 'Технологии. Лидерство. Возможности человека.', backTop: 'Наверх',
  },
};
