export const extraLocales = {
  es: {
    name: 'Timothy Ivaikin', nativeName: 'Español', path: '/es/about/', locale: 'es_ES',
    title: 'Timothy Ivaikin — fundador de Edge Ecosystem y EdgeFocus',
    description: 'Emprendedor y fundador de Edge Ecosystem. Timothy Ivaikin reúne software, infraestructura de TI y equipos para lanzar productos y servicios digitales.',
    skip: 'Ir al contenido', navLabel: 'Navegación principal', languageLabel: 'Elegir idioma',
    nav: ['Proyectos', 'Ideas', 'Contacto'],
    role: 'Emprendedor. Fundador. Autor.',
    firstName: 'Timothy', lastName: 'Ivaikin',
    hero: 'Productos digitales. De la necesidad del negocio al lanzamiento.',
    intro: 'Ayudo a propietarios y directivos a lanzar productos y servicios que requieren software, infraestructura de TI y un equipo organizado.',
    cta: 'Hablemos de un proyecto', secondaryCta: 'Conoce mi trabajo',
    portraitAlt: 'Retrato de Timothy Ivaikin', portraitCaption: 'Fundador de Edge Ecosystem',
    identity: 'Fundador de Edge Ecosystem. Creador de EdgeFocus junto con mi equipo. Autor de Good Results y Shattering Limits.',
    workEyebrow: 'Qué construyo', workTitle: 'Negocio, tecnología y personas. Conectados.',
    workIntro: 'Dirijo la ejecución técnica: desde entender la necesidad del negocio y reunir al equipo hasta la implementación y la aceptación del resultado acordado.',
    ecosystemCategory: 'Empresa', ecosystemTitle: 'Edge Ecosystem',
    ecosystemBody: 'Junto con mi equipo, desarrollo portales para clientes, sistemas internos y automatizaciones para que los clientes accedan a servicios en línea, el personal trabaje sin introducir los mismos datos varias veces ni transferirlos manualmente, y los directivos puedan ver el estado de las operaciones.',
    ecosystemExamples: ['Servicios para clientes', 'Sistemas internos de negocio', 'Integración y automatización'],
    ecosystemLink: 'Conoce Edge Ecosystem',
    focusCategory: 'Producto', focusTitle: 'EdgeFocus',
    focusBody: 'Un espacio de trabajo para notas, objetivos, proyectos y acciones. Un producto que creé con mi equipo para conectar la visión de conjunto con el trabajo diario.',
    focusExamples: ['Captura lo importante', 'Vincúlalo a un objetivo', 'Elige la siguiente acción'],
    focusLink: 'Conoce EdgeFocus',
    philosophyEyebrow: 'La dirección de mi trabajo',
    philosophyTitle: 'Más posibilidades para las personas.',
    philosophyBody: 'Quiero que los productos que construyo amplíen lo que las personas pueden hacer y mejoren su forma de vivir. Esto conecta mi trabajo en tecnología con mi interés por el liderazgo y el desarrollo personal.',
    methodEyebrow: 'Trabajar juntos', methodTitle: 'Empezar por el resultado que las personas necesitan.',
    methods: [
      ['Entender la situación', '¿Quién utilizará el producto? ¿Qué necesita cambiar? Definimos el problema, el resultado deseado y los límites del trabajo.'],
      ['Conectar las partes', 'Reunimos software, infraestructura y personas en un plan de ejecución con responsabilidades y dependencias claras.'],
      ['Llevarlo a la práctica', 'Acordamos cómo se aceptará el resultado, lo entregamos en etapas delimitadas y planificamos teniendo en cuenta a quienes lo operarán.'],
    ],
    ideasEyebrow: 'Textos y conversaciones', ideasTitle: 'Las ideas detrás del trabajo.',
    interviewTag: 'Conversación', interviewTitle: 'Equipos, sistemas y taichí',
    interviewBody: 'Una conversación sobre liderazgo, la preparación del sistema que sostiene el trabajo y cómo crecer sin perder a las personas que participan.',
    interviewMeta: '47 min · Audio en ruso · Subtítulos en inglés', interviewLink: 'Explora la conversación',
    interviewPath: '/en/interviews/tai-chi-business/',
    booksLabel: 'Libros', bookOneBody: 'El arte de la eficiencia para un gran crecimiento.', bookTwoBody: 'Desarrollo personal para el éxito y el empoderamiento.',
    bookLink: 'Detalles del libro', writingLink: 'Lee mis artículos en Medium',
    faqTitle: 'Algunas respuestas útiles',
    faqs: [
      ['¿Quién es Timothy Ivaikin?', 'Timothy Ivaikin (Тимофей Ивайкин) es emprendedor, fundador de Edge Ecosystem, creador de EdgeFocus junto con su equipo y autor de Good Results y Shattering Limits.'],
      ['¿En qué podemos trabajar juntos?', 'En productos y servicios digitales que requieren software, infraestructura de TI y un equipo coordinado: portales para clientes, sistemas internos, integraciones y automatizaciones. Empieza por la situación del negocio y el resultado que necesitas.'],
      ['¿Puedo invitarte a una entrevista o a un evento?', 'Sí. Envíame el tema, el público, el formato y las fechas propuestas. Algunos temas relevantes son la creación de productos digitales, el liderazgo, la delegación y la organización del trabajo.'],
    ],
    contactEyebrow: 'Hablemos', contactTitle: '¿Qué quieres crear?',
    contactBody: 'Cuéntame qué debe funcionar, para quién y en qué punto estás. Para una colaboración, entrevista o invitación a dar una charla, incluye el tema y las personas involucradas.',
    telegramLabel: 'Escríbeme en Telegram', emailLabel: 'Escríbeme por correo',
    contactNote: 'Una presentación breve y concreta es un buen punto de partida.',
    footerNote: 'Tecnología. Liderazgo. Posibilidades humanas.', backTop: 'Volver arriba',
  },
  zh: {
    name: 'Timothy Ivaikin', nativeName: '中文', path: '/zh/about/', locale: 'zh_CN',
    title: 'Timothy Ivaikin — Edge Ecosystem 与 EdgeFocus 创始人',
    description: 'Timothy Ivaikin 是企业家、Edge Ecosystem 创始人。他将软件、IT 基础设施与团队协作结合起来，推动数字产品与服务上线。',
    skip: '跳转到正文', navLabel: '主导航', languageLabel: '选择语言',
    nav: ['项目', '思考', '联系'],
    role: '企业家。创始人。作者。',
    firstName: 'Timothy', lastName: 'Ivaikin',
    hero: '数字产品：从业务需求到上线。',
    intro: '我帮助企业所有者和管理者推出需要软件、IT 基础设施及团队协作的产品与服务。',
    cta: '聊聊你的项目', secondaryCta: '了解我的工作',
    portraitAlt: 'Timothy Ivaikin 肖像', portraitCaption: 'Edge Ecosystem 创始人',
    identity: 'Edge Ecosystem 创始人。与团队共同打造 EdgeFocus。《Good Results》和《Shattering Limits》的作者。',
    workEyebrow: '我在构建什么', workTitle: '连接业务、技术与人。',
    workIntro: '我负责技术交付：从理解业务需求、组建团队，到实施和验收双方约定的成果。',
    ecosystemCategory: '公司', ecosystemTitle: 'Edge Ecosystem',
    ecosystemBody: '我与团队共同构建客户门户、内部系统和自动化流程，让客户能够在线获取服务，让员工无需重复录入和手动传递数据，让管理者能够了解业务运行状态。',
    ecosystemExamples: ['面向客户的服务', '内部业务系统', '系统集成与自动化'],
    ecosystemLink: '了解 Edge Ecosystem',
    focusCategory: '产品', focusTitle: 'EdgeFocus',
    focusBody: '用于记录笔记、目标、项目和行动的工作空间。我与团队共同创建这款产品，将整体方向与日常工作联系起来。',
    focusExamples: ['记录重要信息', '关联目标', '选择下一步行动'],
    focusLink: '了解 EdgeFocus',
    philosophyEyebrow: '工作背后的方向',
    philosophyTitle: '为人们创造更多可能。',
    philosophyBody: '我希望自己构建的产品能够拓展人们的能力，改善他们的生活。这也是我的技术工作与领导力、个人成长兴趣之间的联系。',
    methodEyebrow: '如何合作', methodTitle: '从人们需要的结果出发。',
    methods: [
      ['理解现状', '谁会使用这个产品？需要改变什么？我们一起明确问题、预期结果和工作范围。'],
      ['连接各个部分', '将软件、基础设施和人员纳入同一交付计划，明确责任与依赖关系。'],
      ['投入实际使用', '约定成果的验收方式，按明确的阶段交付，并为后续负责运营的人做好规划。'],
    ],
    ideasEyebrow: '写作与对话', ideasTitle: '工作背后的思考。',
    interviewTag: '对话', interviewTitle: '团队、系统与太极',
    interviewBody: '一场关于领导力、如何为工作打好系统基础，以及如何在成长过程中留住团队成员的对话。',
    interviewMeta: '47 分钟 · 俄语音频 · 英语字幕', interviewLink: '了解这场对话',
    interviewPath: '/en/interviews/tai-chi-business/',
    booksLabel: '书籍', bookOneBody: '以效率推动成长的艺术。', bookTwoBody: '通过自我提升追求成功与自主能力。',
    bookLink: '查看书籍详情', writingLink: '在 Medium 阅读我的文章',
    faqTitle: '几个常见问题',
    faqs: [
      ['Timothy Ivaikin 是谁？', 'Timothy Ivaikin（Тимофей Ивайкин）是企业家、Edge Ecosystem 创始人，与团队共同打造 EdgeFocus，也是《Good Results》和《Shattering Limits》的作者。'],
      ['我们可以在哪些方面合作？', '需要软件、IT 基础设施与团队协作的数字产品和服务，包括客户门户、内部系统、系统集成与自动化。请先介绍你的业务现状和需要达成的结果。'],
      ['可以邀请你参加访谈或活动吗？', '可以。请提供主题、受众、形式和拟定日期。相关话题包括数字产品开发、领导力、授权委派和工作组织。'],
    ],
    contactEyebrow: '联系我', contactTitle: '你正在构建什么？',
    contactBody: '请告诉我需要实现什么、为谁服务，以及目前处于哪个阶段。如果你想探讨合作、安排访谈或邀请演讲，请说明主题和参与者。',
    telegramLabel: '通过 Telegram 联系我', emailLabel: '发送邮件',
    contactNote: '简短、具体的介绍，是一个好的开始。',
    footerNote: '技术。领导力。人的可能性。', backTop: '返回顶部',
  },
};
